### ISSUE TITLE
Allow pull to return additional information / warnings back to client

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#13]
For example, if the pull to client-view fails, it would be useful for debugging to report this back to the client so it can show up in a console.

This also relates to refreshing the data layer auth token, but that's a slightly different bug.

**Comment by phritz** [comment]
i think we want to be able to take programmatic action on these bits of additional info (eg, auth errors) as well as return human readable strings that are helpful for debugging. proposal: introduce some enums that programs can take action on and return zero or more of them along with a human readable string for each. for example:
```
type InfoType string
const (
  ClientView403 = InfoType "ClientView403"
  ClientViewBadRequest = "ClientViewBadRequest"
  ...
)
type Info struct {
  Type InfoType
  Message string
}

type PullResponse struct {
  ...
  Infos []Info{}
}
```

Whatcha think?

**Comment by aboodman** [comment]
Makes sense, but can there truly be more than one of these at a time? Maybe just have one. Remember that this isn't public interface that we need to maintain. The bindings statically link the client, so there's no need to think forwardly at all. We can just change it when we need to change it.

**Comment by aboodman** [comment]
OTOH, I see where you're going here too and there's no downside. Either way is fine w/ me.

**Comment by phritz** [comment]
i went with something very specific, just returning the status code and any error message from the diffserver (eg, unparsable client view response). we can generalize later if we want.
