### ISSUE TITLE
Disable /inject from production

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#16]
It would eventually be useful for production, but is mainly needed in development right now.

**Comment by phritz** [comment]
a common pattern for deciding which things get hooked up in which environments is to pass handlers and their paths into the constructor that creates the service. the set of handlers is usually set up ahead of constructing the service. in this case i'm just going to add a flag to the service that controls whether inject is set up but if we keep finding the need to do things like this we should refactor to a more general approach.

**Comment by phritz** [comment]
fyi you now need to specify --enable-inject on the diffs command line to enable injection
