### ISSUE TITLE
Milestone 1: First Customers using Replicache via Flutter

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#2]
Goal: Get Turtle plus two other new Flutter customers actively integrating Replicache.

Requirements:

1. [Upstream Sync](https://github.com/rocicorp/replicant-server/issues/30)
1. [Downstream Sync](https://github.com/rocicorp/replicant-server/issues/35)
1. [Implement LtHash (or something)](https://github.com/rocicorp/replicant-server/issues/31)
1. [Remove Bundle from Client and Bindings](https://github.com/rocicorp/replicache/issues/5)
1. [Implement Simple Subscriptions](https://github.com/rocicorp/replicache/issues/6)
1. [Sample App](https://github.com/rocicorp/replicant-server/issues/37)
1. Completed Design Doc
1. Simple User Documentation

**Comment by phritz** [comment]
see also #3
