### ISSUE TITLE
Flesh out login in the sample app ever so slightly more

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#25]
Right now the userID is hard-coded into the sample app. Let's push this one step further to completion. After this it would actually be possible to use the Todo app by multiple humans on phones.

* [x] On first-run the TODO app should ask the user for their _email_ address. There will be no verification of the _email_ address at all.
* [x] Use the _email_ to login to the data layer. This returns a _user ID_.
* [x] The _user ID_ itself will be sent as the auth token to the data layer.
* [x] The _user ID_ and _email_ address of the current user will be stored persistently in the client so that when it starts up offline it still knows it.
* [x] It will be possible to "log out" of the client by just clearing the stored email address
* [x] There is machinery in Replicache client currently to create multiple named caches. Use this to create one for each user so that we can demonstrate switching users offline and without redownloading everything.
* [x] Deal with `badAuth`

On the backend this implies:

* [x] Adding email address to User table
* [x] Adjusting the create-todo handler and a few other pieces

**Comment by arv** [comment]
Looks good. I'll take `replicache-client` and `replicache-sdk-flutter` part of this

**Comment by phritz** [comment]
LGTM.
