### ISSUE TITLE
Milestone 2: First Customers Running in Development

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#3]
What do we need to support the first customers running in development (not production)?

- [Ghetto GC on the clientside](https://github.com/rocicorp/replicant-client/issues/1)

**Comment by phritz** [comment]
Possible housekeeping stuff around this milestone:
- CI
- branch protection / audit github settings eg how we get prs and forkability
- logging
- monitoring
- protocol upgradability
- gofmt/lint, clean up warnings
