### ISSUE TITLE
Publicly Available Product v0

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#31]
This bug describes the big picture and motivation behind [Milestone 1](https://github.com/rocicorp/replicache/milestone/1).

(It's here because [Milestones can't have rich text](https://github.com/isaacs/github/issues/1579), grr)

I believe that our next major product milestone should be a public announcement of a working product that anyone can download and try.

Why is a public announcement important? The majority of attention from our marketing announcement came through social media (by far). The vast majority of the sign-ups were people we didn't have any connection to personally. So reaching out to contacts to try Replicache individually is naturally extremely limited. Especially given that the effort to try Replicache is relatively high. The probability of turning any individual contact into a sale is low. We need broad reach.

What is required for a public announcement? It's foggy, but it should intuitively be "a complete product". Or using the popular metaphor, it should be a scooter:

![The Skateboard Philosophy of Product Design](https://raw.githubusercontent.com/rocicorp/replicache/master/skateboard.png) 

What is missing for Replicache to be a scooter? This is a bit subjective, but to me, it feels like:

* Accounts, so anyone can try it by themselves, in production, without having to setup infrastructure
* License and pricing, so people know what they're getting into
* Simple client-side GC, so Replicache is deployable
* Bidirection sync (write transactions and push), because that's the fundamental promise of Replicache

At that point, Flutter mobile app developers could try Replicache by themselves to get simple bidirectional offline sync. There would still be many, many things left to get to a car:

* Push, to get responsiveness up higher
* Delta support for client view
* Larger payloads for client view
* Bindings for other environments
* Dramatically smaller client side binary
* Indexes in the client
* ... etc ...

This milestone associated with this bug will include these tasks and any others we identify as being prerequisites for a public announcement.

**Comment by phritz** [comment]
> a working product that anyone can download and try.

To be clear, we are setting this miletone's bar at 'we have a minimal but complete product that customers can **try**' as opposed to 'a minimal but complete product customers can **use in their app for real, non-expiramentally, in production, with real end users**?

**Comment by aboodman** [comment]
The first one, but mainly because I don't think we know what is required for the second one until we have people doing the first one.

**Comment by phritz** [comment]
Potential additional items:
- #24 fix findgenesis
- i think we should require a better slack story for this milestone https://github.com/rocicorp/replicache/issues/29
- is https://replicache.dev/ what we want and should we maybe take replicate.to down? do we care about roci.dev landing page?
- do we need anyone to agree to a ToS?
- think we should have a canonical way eg mailing list to announce things to our users. hey we found a security bug you need to update. hey there is a new version. etc
