### ISSUE TITLE
Unit test the Flutter bindings somehow

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#46]
I can think of a few ways, increasingly ambitious:

1. Mock out `repm` and just test the bindings. It seems like the `replicache` package doesn't rely on any Flutter machinery except MethodChannel so this should be easy.

2. Include `repm` but fake `MethodChannel` and skip the ios/android code. This implies actually having a desktop build of `repm`, which would be additional but easyish work.

3. Include `repm` and the ios/android code. This seems difficult -- we'd have to fake out `MethodChannel` in the Flutter code, ios, and android. But this would give us the most coverage.

4. Another option completely could be to try and get the whole thing working on Flutter desktop. If it uses the same machinery - `MethodChannel` and friends - maybe that would make the most sense!

**Comment by aboodman** [comment]
5. Oh apparently it's also possible to script the simulator (atleast ios) so you could actually test the whole thing end-to-end, but pretty slow.

**Comment by arv** [comment]
Re 1. The problem with mocking responses is that things get out of sync. If we could test the wire data both in the client and sdk . Maybe if we had a way to record and replay the data this kind of test would be less brittle (pretty hand wavy...)

**Comment by arv** [comment]
We talked a bit about this yesterday and we came up with an alternative plan

## Repm Test Server

We will add another interface to the [Client](https://github.com/rocicorp/replicache-client) that exposes the [`repm` `Dispatch`](https://github.com/rocicorp/replicache-client/blob/730e2302674ec0c97ba612496ae1d6a58af7072e/repm/repm.go#L66) function over HTTP. This will only be used for testing and will require manually starting the server before running the binding unit tests.

From the binding side we can override [`Replicache` `_invoke`](https://github.com/rocicorp/replicache-sdk-flutter/blob/master/lib/replicache.dart#L324-L333) to call the server instead.
