### ISSUE TITLE
Update design doc to reflect ability for data layer to make mutations asynchronously

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#47]
The design doc predates the idea that mutations can be applied asynchronously. This is important and cool, it should show that.

https://github.com/rocicorp/replicache/blob/master/design.md#sync

**Comment by phritz** [comment]
https://github.com/rocicorp/replicache/commit/e496adf024ab969de7b3f02a4432661585264bd7#diff-83772ba7ad0304b1562d08f190539946
