### ISSUE TITLE
Few issues running the redo sample

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#48]
1. Scary looking error on every pull:
<img width="1440" alt="Screen Shot 2020-04-28 at 1 25 04 AM" src="https://user-images.githubusercontent.com/80388/80482061-40909580-88ef-11ea-836f-eb68805d62f6.png">

2. Error above formatted badly so that message not visible.

3. Crash when adding a new todo:
<img width="1430" alt="Screen Shot 2020-04-28 at 1 25 36 AM" src="https://user-images.githubusercontent.com/80388/80482147-674ecc00-88ef-11ea-8d99-f9eb95394e27.png">

4. Error above also formatted badly.

**Comment by arv** [comment]
I don't see 3/4.

**Comment by aboodman** [comment]
3/4 are caused by a null list id. This happens if the user you login as doesn't have at least one list. Seems like we should implicitly create a first list when a user is created on the backend for now, and take the lists picker out of the UI probably too.
