### ISSUE TITLE
Flutter SDK: Adopt test mode to work during development too

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#58]
Building and linking replicache-client during iteration is super painful. Now that we have a version of replicache-client that can serve over http, let's just add some switch to be able to use that during development too.

**Comment by aboodman** [comment]
I think this is likely how electron integration should work, at least until we have a wasm build, so it's doubly useful.

**Comment by arv** [comment]
It works now but maybe we want to make it easier to turn it on (in the UI or with a global var in the code)

**Comment by aboodman** [comment]
Good enough.
