### ISSUE TITLE
Tag all the repos?

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-old#60]
Right now we tag rocicorp/replicache ande we roll the deps -- https://github.com/rocicorp/replicache/commit/e2d0c853916909f67f6fa4e61e299bbd56661c6e

It would be nice if we could tag those commits in the different repos too.

**Comment by aboodman** [comment]
Yeah I don't really like the way the release "process" is working now. I thought I'd try it this way, but it was a failed experiment.

The main problem for me is that it is very mentally taxing to create a release because I kind of have to think about all the repos wholistically. I'm not sure why that hurts, but it does. For some reason it feels like it would be easier tor release each repo separately, then do an SDK release.

**Comment by aboodman** [comment]
For the flutter SDK I agree. For one thing this is how the Flutter ecosystem works -- libraries need to use semver. Same for pretty much all the other bindings layers.

For repm, I actually was thinking the other way. We have no API guarantee for repm and don't want to - it's a private internal detail. So I was going to change the build system to just use the hash as the version.

(Also as a practical matter, using major version numbers > 1.0 in Go is a huge pita).

For diff-server I'm not actually sure how versioning should work. The practice in golang as I understand it is to version as per the *Go* interfaces. What should you do for servers where the interface is HTTP? I guess I'd try to follow the semver convention, but applied to the HTTP interface not the Go inteface.

And then I think I'd ideally like to get rid of the packaged up SDK download if possible. It ended up being more effort than it was worth. I think that when people are e.g., trying out Replicache for JS, there should be two steps:

1. npm install `replicache`
2. dl the `repl` CLI from replicache.dev, which is used to do acct management and includes a dev diffserver and everything else

**Comment by aboodman** [comment]
Were you by chance asking this because ToT just broke the flutter bindings? I saw that.

Flutter bindings used to rely on a specific version of replicache-client. When I went to this new build system I took that out. Not sure what I was thinking. It doesn't work very well. Putting it back now :(.

**Comment by arv** [comment]
> Were you by chance asking this because ToT just broke the flutter bindings? I saw that.

I didn't see that but I had to rebuild the client libraries

**Comment by aboodman** [comment]
I'm planning to redo how we do releases. I still don't really understand what your motivation is here... can you clarify so I can know whether what I'm doing will address whatever the problem was?

**Comment by arv** [comment]
I wanted to check out the commit for release X.

**Comment by aboodman** [comment]
ah

**Comment by phritz** [comment]
Can we close this?

**Comment by arv** [comment]
Closing. Let's see if there is a new need in the future
