### ISSUE TITLE
upstream sync / client followups

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache-old#61]
- [ ] 1. fix sync return value https://github.com/rocicorp/replicache-client/pull/87#pullrequestreview-411362186
- [x] 2. add replay to the sync_integration_test
- [x] 3. limit batch push payloads to 4MB. we should not accept a mutation on the client that is > 4MB *and* we should stop adding pending mutations to the push payload and send it when it is >= 4MB. and we need this in the docs.
- [x] 4. In https://github.com/rocicorp/replicache/issues/30#issue-599410531 i proposed some invariants that we should check during sync to reduce the chances that we have a bug / data corruption. i had planned to do that here https://github.com/rocicorp/replicache-client/blob/8defd6d1ad365de4de3e34b2c5bed2c014ff3408/db/sync.go#L130
- [x] 5. fix sandbox auth, which is hardcoded
- [x] 6. per discussion here https://github.com/rocicorp/replicache/issues/8 separate the role of clientid into two separate things
- [x] 7. add timeouts to all outgoing network connections. **super important!** the http client default is no timeout. (this is one of those things that had we chose to lock during sync could have killed us.)
- [x] 8. take a pass through designdoc and update anything that has changed

**Comment by aboodman** [comment]
Thanks, let me think about this.

**Comment by aboodman** [comment]
(3), (4), and (6) are good ideas but I think we should do later. Don't seem critical. Nice fallout of the sync protocol that (3) is even possible! Create bugs?

The remainder I do want to do right away. I will do (1), can you do the others? (I assume that (5) is not a big design issue, just plumbing another parameter through from `BeginSync`) ?

**Comment by phritz** [comment]
yes to each of the three questions

**Comment by phritz** [comment]
1: you are on top of this in https://github.com/rocicorp/replicache/issues/53
2: https://github.com/rocicorp/replicache-client/pull/93
3: https://github.com/rocicorp/replicache/issues/62, https://github.com/rocicorp/replicache/issues/63
4: https://github.com/rocicorp/replicache/issues/64
5: https://github.com/rocicorp/replicache-client/pull/93
6: nop
7: https://github.com/rocicorp/replicache-client/pull/94
8: https://github.com/rocicorp/replicache/commit/5f5b2eea0103017fd5a90587f5a1827053617a65#diff-83772ba7ad0304b1562d08f190539946
