### ISSUE TITLE
Perhaps we should expose push and pull directly to bindings, rather than BeginSync

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#72]
Currently, we are syncing on a loop. But once we introduce push, it looks a little different:

1. user code writes a transaction
2. some debouncing occurs
3. We sync, which means:
  a. push the change to batch endpoint
  b. **immediately pull**
5. batch endpoint pokes all the relevant clients that something has changed, which includes us
6. We sync again
  a. BeginSync short-circuits push if there are no pending change
  b. We pull again, which is almost certainly a no-op since we just pulled

Instead, it seems like client should just push when it sees dirty changes, and pull in response to pokes from server, other interesting transitions (startup, like network on/off), and maybe a just-to-be-safe coarse timer.

**Comment by phritz** [comment]
closing in favor of https://github.com/rocicorp/repc/issues/182
