### ISSUE TITLE
First Batch of User Requests

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#76]
1. Fetching the entire client view over and over is too expensive (in dollars, latency, quota). If our backend services have a way to request coarse changes is there a way to take advantage of that?

2. Fetching the entire client view will take too long. We would like to be able to response to sync (especially first sync, at startup) faster. How can we do this?

3. Some of our customers will have more data than the Replicache size limit. We can fallback to remote, but it's difficult to write code to abstract over the different ways to get data.

**Comment by aboodman** [comment]
(aaron's thoughts, wip)

# 1: Fetching Client View Repeatedly Too Expensive

It is possible right now without any changes to Replicache, to store state on data-layer associated with ServerStateID that could be used to implement differential queries to datalayer's backends. Combined with a data-layer-side cache of the client view, this could be used to answer (1).

However, we could make this easier with two new features to Replicache:

a) [ClientView Cookies](#74) would eliminate the need to store state associated with ServerStateID on data-layer side, by stashing it with the Client View itself.
b) [JSONPatch for ClientView](#75) would eliminate the need to store a cache of the Client View at data-layer

# 2: Fetching Entire Client View Takes too Long

If the client view takes a very long time to build then it seems like data layer is going to need to build it up slowly and stash it somewhere, temporarily, as it works (e.g., in Redis or Memcached or whatever).

The client can use state that is in the client view to know whether its view is incomplete and to re-query periodically for changes. Or if the server has a push channel it can poke the client to re-fetch when something has changed.

Question: If the data layer is going to maintaining a cache, should it just play the role of diff server? It's not that hard.

# 3: Fallback to Remote

Idea: Use the Client View itself as the way to communicate *all* data the client needs. So take a user who has 100MB of data. Customer reserves 15MB of data for persistently cached offline state, as we use Replicache now.

Remaining 5MB of data is used more like a classic LRU cache. As the user navigates around the app, client makes mutations (normal offline-first mutations) that inform data-layer of what client is trying to look at. data-layer records this information, associated with ClientID and uses it when building Client View to populate LRU part of Replicache.

This again can be implemented today without any changes to Replicache. However, it can be made easier by those same two bugs:

a) [ClientView Cookies](#74) would eliminate the need to store view state associated with ClientID
b) [JSONPatch for ClientView](#75) could conceivably make these syncs much faster by enabling data-layer to respond initially with only the changes needed for the requested view.

It's worth noting that even with (a) and (b) the client will still have to do two requests (push, then pull) to change views rather than 1 which would be more typical with classic designs. We could eliminate that first push request a few different ways -- either #72, which would enable client to just pull first, or by enabling mutations to be marked local-only, in which case the client could realize it doesn't need to send them as part of push.

**Comment by phritz** [comment]
Great to have this feedback, questions below.

> Fetching the entire client view over and over is too expensive (in dollars, latency, quota).

I know it is expensive in these things but it would be helpful to know a bit more specifics. How much is too much and where do we stand now? Which of these is the most important? Are these things a problem now or will they be a problem at X users and if so what is X?

> Fetching the entire client view will take too long. 

Same desire for specifics. How long does it take and what is acceptable? What are the component contributions to what is making it slow?

> Some of our customers will have more data than the Replicache size limit

Indeed. Are cron and laserfocus thinking they will need > 20MB out of the gate? Or at some point soon? Or are we talking about future customers?

**Comment by aboodman** [comment]
I'm just going to close this. This wasn't a useful medium for this discussion :). Will leave other two detailed bugs open.
