### ISSUE TITLE
RFC: enable customers to return incremental clientview updates

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache-old#79]
Status: as of Oct 16 2020 general agreement that we should probably NOT go this far; instead we should make more minimal changes to the existing protocol for now

### Related Issues
- this present issue will close https://github.com/rocicorp/repc/issues/177 
- this present issue lays the groundwork for https://github.com/rocicorp/replicache/issues/75 in the sense of supplying a way to do checksums with incremental patches without having to store the whole map
- this present issue specifically excludes from scope https://github.com/rocicorp/replicache/issues/74 

### Background / Rationale
During pull, the diffserver expects the customer's data layer to return the full client view. This is easy to implement for some customers: they just pull the data out of their store and return it. However we have at least one customer for whom it is _not_ easy. Specifically the canonical store for their data is a third party api that forces slow, serialized requests to build the full client view. Rebuilding the full client view is expensive for them in terms of time, which makes sync appear sluggish: a small change is committed in one instance of replicache, pushed up to their data layer, but then there is a multi-second pause as the data layer builds the client view before the change flows down into another instance of replicache. 

Happily the third party API provides a way to receive an incremental update from a previous state. In principle our customer could keep a copy of a user's client view in their data layer and in response to a request from replicache for the client view pull just the incremental update from the third party, apply it to the customer's copy, and return the full view to replicache. To do this the customer needs to keep a map from replicache clientid (which is passed in the client view request) to client view and associated metadata (eg, whatever incremental update cookie or similar it has from the third party api for that state). This works but is a bit of a hack and makes the diffserver redundant (the customer has a patch, applies it, returns the full view to the diffserver which promptly diffs it to derive what the customer started with, meanwhile adding two http round trips to the mix). 

So the question is whether we want to encourage customers do this hack or provide a better way to do incremental updates. We propose to provide a better way to do incremental updates because:
- while an easy way to get started, returning the whole client view every pull becomes increasingly untenable as client view size increases, and we know we want to lift the current size limit.
- some customers can already easily generate diffs themselves and would like to use them directly.
- we should provide first-class support for common scenarios and expensive-to-build client views keep cropping up
- enabling customers to provide their own diffs is consistent with our it-should-work-like-a-library-not-a-framework philosophy

### Problem statement

Replicache should provide efficient, first-class support for customer-generated client view diffs.

Not in scope of this problem statement:
- lifting our current size limits
- repliache-level support for client view windowing over a much larger virtual client view
- supporting transports other than http
- replacing how the diffserver patches (though we do move to checksum that is compatible with field-level patching, we are not moving to field-level patching in diffserver as part of this effort)

### Proposal

Let's enable customers to cut out the diffserver and directly provide updates, incremental or otherwise, to the replicache client. And since an incremental update and a full update differ only in the amount of data they return, not in what they are composed of -- keys and values -- let's also do away with the syntactic and conceptual distinction between the the incremental update provided by the diffserver and the full update provided by the data layer client view. They are both just updates.

Conceptually, the client makes an `UpdateRequest` to something that can provide client view updates. This might be the diffserver or it might be an interface on the customer's data layer. Replicache shouldn't care. In response it receives an update which may or may not be incremental.
```
              Conceptual Model

+-------+
|  App  |
|       |
+-------+  UpdateRequest
+-------+ +------------>  +------------+
| Client|                 | ClientView |
+-------+ <------------+  +------------+
          Update Response
          (full or delta)
```

Replacing the conceptual "ClientView" box on the right with the DiffServer and customer data layer looks like the following. 
```
              Using the DiffServer

+-------+
|  App  |
|       |
+-------+  UpdateRequest  +------------+  UpdateRequest  +------------+
+-------+ +------------>  |            | +------------>  |  Customer  |
| Client|                 | DiffServer |                 | ClientView |
+-------+ <------------+  |            | <------------+  |            |
          UpdateResponse  +------------+ UpdateResponse  +------------+
              (delta)                         (full)
```
The client sends an UpdateRequest to the diffserver, which in turn makes an UpdateRequest to the customer's data layer. The data layer returns a full client view in the UpdateResponse. The DiffServer diffs the full update against the DiffServer's copy of the client's current state and returns an incremental UpdateResponse to the client. 

For customers who can return their own deltas, we skip the middle man:
```
              Not using DiffServer

+-------+
|  App  |
|       |
+-------+  UpdateRequest +------------+
+-------+ +------------> |  Customer  |
| Client|                | ClientView |
+-------+ <------------+ |            |
          UpdateResponse +------------+
          (full or delta)
```
The client makes an UpdateRequest directly to its data layer which returns the delta.

(As an aside, consider that this suggests that potential customers kicking tires don't have to create an account or use the diffserver at all to get started: they can just point their client directly at a client view in their data layer that returns the full client view every time.)

(Yet another aside: the UpdateResponse will contain an Update, which could be delivered to the client in whatever way makes sense, eg an update could be pushed over a websocket instead of pulled over HTTP, though that's out of scope for this RFC.)

#### Metadata

We keep or pass around the following bits of metadata to enable update (née pull) to work:
- the client passes its `clientid`
- In order to diff two states a differ needs a unique identifier for each. The diffserver currently uses a _server state id_ string that is kept by the client in its snapshot commit, passed in the [pull request](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/serve/types/types.go#L15), and returned in the [pull response](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/serve/types/types.go#L20). This string is opaque to everything but the diff implementation. In the case of the diffserver it happens to be a noms hash of the noms map of the client view, but in the customer case it could literally be anything cookie-like: a random string, an encoded struct, whatever. It could also be _multiple_ things eg multiple tokens for separate sources of data that go into the client view.
- The diff algorithm used by the diffserver keeps a [checksum](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/serve/types/types.go#L16), a lightweight fingerprint of the contents of the clientview. This checksum is returned with a diff by the diffserver and supplied in the pull request by the client. The client and diffserver use it to ensure that the patch returned by the diffserver has been correctly applied by the client.
- The client supplies a version number indicating what kind of patch it would like to receive.
- The client supplies customer data layer auth credentials.

The metadata exchanged falls into two categories: that which the client controls (clientid, version, data layer auth) and that which the server controls (server state id, checksum) and would like returned to it  in future UpdateRequests, like a cookie.

I think we should expect that the kinds of meta-data that application and client and client view wish to exchange will continue to expand and evolve. Currently this metadata is passed through structure fields in the [PullRequest](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/serve/types/types.go#L9) which is nice in that it easy to hand-craft, validate, and understand, but it is inflexible and not customizable. In the client the metadata is stored in the Commit itself (or sometimes supplied by the app via rpc), meaning that any time we want to add a new metadata field we change the structure of the Commit.

Because we expect meta-data to expand and evolve we plan to solve the problem in a more generalized fashion than just say adding a "cookie" field to the UpdateRequest, which would be the minimal delta.

##### The /r/cookie keyspace

To solve the problem that the server wants to return metadata to the client to be returned to it during update, we enable the server to store it like any other data in replicache. Let's call this data "cookies" and designate a portion of the keyspace for them, eg `/r/cookie`. These keys may be updated like any other key in the patch returned in the UpdateResponse. They could also be set directly by the client, though we would not expect them to be. The client includes all the keys under `/r/cookie` and their values in an UpdateRequest. Cookie values are pulled from the base snapshot.

Only data that is strictly controlled by the server can move into cookies. The checksum does not move in because `/r/cookie` is part of the map the checksum is over. But the server state id, which is a cookie, does move in. Other metadata like clientid and version do not move in because the client is the source of truth for them. 

Aside: we can imagine a separate "mount point" for client-controlled keys that works analogously to the server-controlled keyspace we have today, but we don't have a need to call it into existence at the moment, so leaving that for future discussion.

##### Should we use the /r/signal keyspace for signaling?

Currently we return information about what happened during push and pull in the BeginSyncResponse's SyncInfo.BatchPushInfo and .ClientViewInfo. We do this for informational purposes but also to support re-auth: if during push or pull the client or the diffserver gets a 401 from the data layer then the app needs to re-auth. The implementation of this is a [bummer](https://github.com/rocicorp/repc/issues/171): we return the data layer status code in the ClientViewInfo but if BeginSync returns an error we don't get it -- we return an error instead of the BeginSyncResponse. Since the error returned is a string, the bindings have to do a regexp match on it for the specific error "FetchNotOk(4\d\d)" _in addition to_ checking the SyncInfo.ClientViewInfo.status_code in there is no error. 

This kind of thing is one reason that it is common for RPC protocols to signal errors within the RPC response, instead of separate from it. For example, the [account service](https://github.com/rocicorp/account-service/blob/e07de54c1cf601ecb01b743ddd8078061333821d/rpc/wrapper.go#L42) does this and is a much lighterweight version of grpc's [rich](https://cloud.google.com/apis/design/errors#error_model) [errors](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto). So that is one option to address the above problem.

A different mechanism would be use keyspace. We could by convention use `/r/signal` for the server to signal something to the client. For example the diffserver could return the key `'/r/signal/client-view-request/http-status-code' => 401` as part of its response to the client. Since this is just a normal key, the bindings or app could have a subscription to it and respond appropriately. In order for this to work the server does need to remember to update the fingerprint (see below) to include the new value.

#### Patch & Fingerprint

To unify the pull response and the client view response we need to reconcile the difference in how the diffserver and client view return json values. Recall that [it was decided](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/kv/patch.go#L38) that the diffserver [returns patch values as a string containing json](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/kv/patch.go#L38) because we didn't have raw json as an option with nanoserde; however we now use serde and so have this option. The client view returns [raw json](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/serve/types/types.go#L37) and we should be using raw json in general.

The bigger issue is however that the current checksumming scheme requires the thing generating the  patch and checksum to have access to the full client view state. The diffserver keeps it, but keeping it would be an onerous requirement for our customers, some of whom just get diffs from a third party service. 

The following is proposal for how to do fingerprinting -- the equivalent of today's checksumming -- in a world where a customer doesn't want to store the full client view and where we support field-level patching: https://github.com/rocicorp/repc/issues/207. 

To be clear, the plan is to use the fingerprints above in updates but to not yet implement field-level patch. 

#### Sample Request/Response using the DiffServer

```
// UpdateRequest Client -> DiffServer; note diffserver auth passed on Authorization header.
{
  // Client-supplied values, these exist today.
  "version": 1,
  "clientID": "<clientid>",
  "clientViewAuth": "<clientviewauth>",

  // Fingerprint is server-controlled, but can't be included in the map because it is a 
  // fingerprint *of* the map. This takes the place of checksum.
  "fingerprint": "<fingerprint>",

  "cookies": {
    "/r/cookie/diff-server/snapshot/base-state-id": "<base state id>",

    // Note: I can't decide if last mutation id should be included in the map.
    // I've included it here as a cookie to see what we think. Normally it is 
    // returned in the UpdateResponse separately from the patch. Another
    // option is to return it in the map but not under /r/cookie -- neither
    // the diffserver nor client view need it. Note this is the last mutation id
    // of the base snapshot.
    "/r/cookie/client-view/last-mutation-id": 20,
  },  
}

// UpdateRequest DiffServer -> Customer ClientView; client view auth passed in Authorization.
// Note that the diffserver does not include its cookies in this request.
{
  "clientID": "<clientid>",

  "cookies": { 
    "/r/cookie/client-view/last-mutation-id": 20,
  },  
}

// UpdateResponse DiffServer <- Customer ClientView
{
  "patch": {
    "ops": {
      { "op": "remove", "path": "" },  // Full sync
      { "op": "add", "path": "/key1", "value": <raw json> },
      { "op": "add", "path": "/key2", "value": <raw json> },
      ...
      { "op": "add", 
        "path": "/r/cookie/client-view/last-mutation-id", 
        "value": 23 },
  } 
}

// UpdateResponse Client <- DiffServer
{
  "patch": {

    "fingerprint": "00a63b8",  
 
    "ops": {
      // Note: no remove of "" so this is an incremental update.
      { "op": "replace", "path": "/key23", "value": <raw json> },
      { "op": "add", "path": "/key17", "value": <raw json> },
      { "op": "remove", "path": "/key200" },
      ...
      { "op": "replace", 
        "path": "/r/cookie/client-view/last-mutation-id", 
        "value": 23 },

      // DiffServer-added values:
      { "op": "replace", 
        "path": "/r/cookie/diff-server/snapshot/base-state-id", 
        "value": "<new base state id>" },
  } 
  
  // TODO what if anything to do about ClientViewInfo. 
}
```

#### Considerations

Customers who take on creating their own diffs take on additional risks: there is more for them to get right. Some specific things that could be tricky:
- handling the case where they receive a cookie for state they don't have
- ensuring they don't accidentally send a diff as a full patch, or vice versa
- ensuring last mutation id is consistent
- if they are keeping their own client view copies around, ensuring that they are highly available
- if they are computing the diff then they have to get their cookie right: it has to change whenever the data changes and not just in response to changes originating on the client
- (what else?) 

#### TODO Customer HOWTO return your own diffs

At the least:
- Ensure last mutation id is consistent with whatever the source of truth is for your data. If you are using a database, this means updating it transactionally during batch push with the data. If you are using a third party API, this might mean something else.
- Implement json fingerprinting if it is not available in your language.
- Have a high-availability way to store the patch table by cache id (nee client id).
- Implement GetUpdate (UpdateRequest) -> UpdateResponse, ensuring:
  - it can return a full sync or a delta
  - it returns a full sync if you get a cookie through config that you dont understand
  - it returns a full sync if the patch table is unavailable
  - that you hear about the patch table being unavailable if it is (or frequently is), and you can handle the increased load of doing full syncs if the patch table is unavailable.
  - that you hear about a jump in full syncs vs patches
  - that you patch your config keys with any cookies that you need
  - that you return the fingerprint in the UpdateResponse and update it in your store

**Comment by aboodman** [comment]
> there's no checksum safety belt unless we give them a way to do it (do they want to?). If their source of truth is a third party api then it is hard for them to be certain that the source of truth and what the client has are identical.

I hadn't completely considered this. It does worry me. Customers who play the role of diff-server could easily get into a situation where client is out of sync with server and nobody knows -- client just acts weirdly.

This one thing - that the client *always* reflects the server state was in my mind a big simplifying attribute of Replicache.

Hm.

> (As an aside, consider that this suggests that potential customers kicking tires don't have to create an account or use the diffserver at all to get started: they can just point their client directly at a client view in their data layer that returns the full client view every time.)

Neat.

> It is dissimilar to the data stored in the value Map in that there is no app-level mutator for a transaction (its just composed of put/get/del)

I don't understand this. Are you saying that there's no JS "mutator" function that is responsible for client-side changes to this data? I don't see why mutations to this data couldn't work exactly the same way as mutations to our current kv data.

> We could provide a flag on opentransaction or a separate OpenConfigTransaction that enables the app to open a config transaction to set config keys and values

> Config keys and values would be stored in a separate Map which is referenced from the Commit, so in addition to its value map the Commit would have a config map.

> Whether we replay config commits is an interesting question that requires a little more discussion if we think we want to go down this route, eliding it for now but asserting that a sensible strategy exists.

I think it would be useful to be able to change config keys and other keys in same transaction, and there's no reason I can see to separate them. It seems to create a lot of extra work to separate them. Why not let user define what the span of keys are that are configuration? Or perhaps we just define that /config/ are configuration?

> Having config keys that work like data keys provides a really neat and tidy way to solve signaling problems. For example currently the http status code of the client view request to the data layer is returned in the ClientViewInfo field as part of the BeginSyncResponse. This is checked manually by js and if it is a 401 app-level data layer re-auth is kicked off. If we had config keys the diffserver could instead return a config patch which sets '/replicache/diff-server/client-view-auth-failed-401' => true. The bindings or the app could have a subscription for this key and would get a notification when it changed. Also, this mechanism could be used not just for update management, but it could be used by the client to keep and communicate metrics (eg, imagine the keyspace /replicache/stats/error-counts/ or /replicache/stats/sync-count/ or similar). Same for the app.

Cooool.

> The question is: should we make this investment now? Note that while it requires work across the stack nothing that is required is new or novel: we already have the patterns and mechanisms.

I feel like if we can agree to just assert that /config/ is special and updates to config keys are otherwise handled as any other update, then there's almost nothing to do here. It's like ... reading a key space and appending to the http tx we're already doing.

> for now keep the current patch model where the granularity of the diff is setting and deleting whole values. We can do #75 or binary diff as a follow-on.

I don't think that this will address the original customer request though. I believe that the underlying Google API only return field-level patches. So if we only support key-level patches, then customer is back to maintaining a history of previous states.

> If we can make checksum work with raw json great

Urgh this stupid bit of code. Several thoughts:

1. Whether strings are embedded or not is orthogonal to checksumming I believe. It's literally just a question of the format of the RPC.
2. Checksums are not going to help customers who are generating their own patches
3. It seems like we *need* to support field-level patches for our customer
4. Field-level patches seem incompatible with our current checksum unless we canonicalize the json

**Comment by phritz** [comment]
__Re Checksum__

> > If we can make checksum work with raw json great
> ...
> 1. Whether strings are embedded or not is orthogonal to checksumming I believe. It's literally just a question of the format of the RPC.

OK right, the string in the pull response is incidental -- if we had had raw json in nanoserde we could have just treated the values as bytes.

I guess the main thing for us to keep in mind is that [if the json is round-tripped anywhere](https://github.com/rocicorp/repc/issues/93#issuecomment-675123657) there is the possibility that the serialized json is not byte-wise equal to what was read. Order of properties in objects could vary, numeric values could be expressed differently (1e3 vs 1000), strings could be expressed differently (\u-escaped vs raw UTF-8), whitespace could be added/subtracted, etc. 

> 2. Checksums are not going to help customers who are generating their own patches

I don't follow this one. They help us and we are generating our own patch. If we can define an easy to implement checksum function everyone could use it.

> 3. It seems like we need to support field-level patches for our customer

OK I missed this requirement. It's a big one. I will need to revise the RFC and my thinking a bit. 

> 4. Field-level patches seem incompatible with our current checksum unless we canonicalize the json

Yeah, I'm afraid you are right. 

At some level the right answer to mitigating client drift is to recommend a full sync at some regular interval (eg every 24h). Low tech but totally feasible given the small data size (4MB) and that the sync happens in the background.

If not, I wonder if we can get away with not properly canonicalizing the json itself which is a fair amount of code or requires a library, but instead create our own canonical form for the purpose of checksumming, more like a fingerprint. We'd want the fingerprint to be both easy to implement and a "good enough" representation of the json to detect large classes of important differences. It would necessarily be lossy: we'd avoid hard or complicated canonicalizations and equivalences or use approximations. For example it's not hard to imagine writing a function using our json fingerprint that for two maps x and y:
   - detects differences in keys of x and y (ie, it tell us x and y have exactly the same keys with high probability)
   - detects structural type differences in the values of x and y (ie, for all keys k in x and y it can tell us with high probability whether x[k] and y[k] have the same type)
   - detects value differences in the values of x and y when doing so is obvious/easy (eg, it detects differences in bools, differences in lengths of arrays, and uses some heuristic for strings and numbers)

One could imagine for a map entry like this:
```
"key5" => {
   "foo": true,
   "bar": { 
      "inner1": [2, 14, 3],
   },
}
```
the fingerprint of the json value might be something like:
```
object { "bar": object { "inner1": ARRAY_NUM_LEN_3 }, "foo": true }
```
and then we define the checksum for this entry to be something like we do in https://github.com/rocicorp/diff-server/blob/master/kv/checksum.go:
```
crc32('key:"key5" value:object { "bar": object { "inner1": ARRAY_NUM_LEN_3 }, "foo": true }')
```
I'm sure we could come up with some heuristics for strings and numbers in the fingerprint that work good enough.

**Comment by phritz** [comment]
__Re Config keys__

> I think it would be useful to be able to change config keys and other keys in same transaction, and there's no reason I can see to separate them. It seems to create a lot of extra work to separate them. Why not let user define what the span of keys are that are configuration? Or perhaps we just define that /config/ are configuration?
> ...
> I feel like if we can agree to just assert that /config/ is special and updates to config keys are otherwise handled as any other update, then there's almost nothing to do here. It's like ... reading a key space and appending to the http tx we're already doing.

Yes the uniformity of a convention like `/config/` is appealing. We'd want to require that they prefix their data keys with `/clientview/` or similar so that we have an insertion point to do a full sync of the client view without nuking the config at the same time (`op=remove path=/clientview/`). Some considerations:
   - unless we did something special the checksum ends up being over the config and data, and I'm not sure that's what we want: like when they receive an UpdateRequest they have to add the /config keys to their copy of the clientview or at least add them to the checksum that they keep. Maybe that's ok, dunno.
   - actually now that i think about it, we can't store the checksum in the map itself!
   - in the updaterequest it's not clear to me that we want to send the config values from the base snapshot or the main head. Like if I have a pending commit that sets data layer auth config key to 'xyz' but the base snapshot has 'abc' i think i would want the latest config value 'xyz' from the pending commit, not the one from the base snapshot. this feels qualitatively different to me than regular data values and local commits. i we could pull them from the head either way, just feels a little weird, not sure that matters.
   - if config mutations are just normal local mutations their data layer has to implement nop mutators for all the special 'set replicache config option X' mutators eg the one that sets the data layer auth. and also for any local-only config that they have (maybe their app wants to keep some data not part of the client view for its own use). i feel like config is more like control / signal channel than data in the sense of the client view. and some config data's canonical location is in repc, not in the data layer (eg, clientid).

Guess it just feels like config is not data to me. Hmmm. Maybe more tomorrow as I keep thinking about it. Tired so calling it for the day.

**Comment by phritz** [comment]
Had a thought about checksumming overnight: we could move it out into the customer's app. Require the customer provide a mutator function that computes a checksum. As part of finalizing sync the bindings invoke it on the sync snapshot commit's new data, ensuring it matches what was gotten from the server. We could provide a default implementation in js and ensure it is easy enough to compute that customer could implement it themselves on the server if need be, or supply something else that works for them. 

Not sure if or how it helps, but it's a possibility.

**Comment by aboodman** [comment]
> though we would not expect them to be

I think over time we will evolve use cases for the client to set them (thinking here of my idea of moving a window through a large data space).

> Should we use the /r/signal keyspace for signaling?

Is the idea that /r/signal would work like normal Replicache state, and would *not* get sent upstream (like /r/cookie)? If so yeah I think I like this idea.

> `// Note: I can't decide if last mutation id should be included in the map.`

Why isn't `last_mutation_id` a signal -> it seems like it fits the requirements: server-controlled, one way message from server to client.

> `UpdateRequest DiffServer -> Customer ClientView;`

How come the fingerprint isn't included in this request? And will it need to be modified by diff-server to remove the keys that diff-server isn't sending along? Also `version`?

**Comment by aboodman** [comment]
A few other things: 

* I see where you are trying to go using the same request types for the link between client and diff-server and diff-server and data-layer, but it makes it seems like the abstraction doesn't quite hold because e.g., in the case where there's a diff server we don't require data layer to return a checksum (and there's no sense in us passing one). Also it's a little silly to have customer return a patch that drops everything everytime. I feel like it would be a little more comprehensible to keep the roles separate and continue to have the same request/response types we have now for the case where diff-server exists.

* It bugs me that now we have `Push`, `UpdateRequest`, and `Rebase`. The names were a family before and the metaphor made sense. Now it feels inconsistent. I am aware that `Pull` is a bit unfortunate if we consider having that data sent over a web socket in the future. Are there other problems with it?

**Comment by phritz** [comment]
Will respond next week but sure we can back off making the more extreme changes.

**Comment by phritz** [comment]
Solved via diffsync.
