### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#8]
The design doc and getting started guides both gloss over the question of authentication.

The current codebase has an [auth mechanism](https://github.com/rocicorp/replicache-client/blob/master/doc/auth.md), but that authenticates clients to the _Replicache_ server. It says nothing about interaction with the data layer. But our design requires that clients also authenticate to the data layer.

Specifically, our auth-related requirements seem to be:

1. The data layer must be able to authenticate the _user_ the client is posting on behalf of, when the client calls the batch endpoint (just as normally, when Replicache is not in the picture)
2. The data layer must be able to authenticate the _user_ the diff server is posting on behalf of, when the diff server calls the client view endpoint.
3. The diff server must be able to authenticate the _Replicache Account_ the client is posting on behalf of when the client fetches diffs to the client view.
4. Eventually, the Replicache service will have a concept of _users_, which will be members of _accounts_, which have billing details and so-on. The Replicache service will need to authenticate the _Replicache user_ that the CLI or UI is posting on behalf of, and to ensure the user is authorized to act on behalf of particular accounts.
5. Auth-related work to integrate should be minimized.

Any other related requirements?

**Comment by phritz** [comment]
- More sophisticated customers are probably going to want to also
authenticate the diff servers. But hopefully we can get away without that
for as long as possible.

- it would be really nice to not have to deal with the complexity of
accounts versus users within the auth system. Like if we could just have
the notion of accounts and provide good client-side CLI tooling to manage
multiple accounts that seems like it might be simpler on our end. Just a
thought.

- as a requirement there probably also needs to be a mechanism for
invalidating replicash authentication or authorization tokens.

- is it a requirement that auth specific errors of each kind are returned
with fine grain fidelity to the binding or user code?

- is it a requirement that eventually there's a mechanism for replicash the
company to help developers recover replicash account credentials or
information if they are lost?

**Comment by aboodman** [comment]
> - More sophisticated customers are probably going to want to also
authenticate the diff servers. But hopefully we can get away without that
for as long as possible.

I meant to capture that with (2) in my original post. Are you saying something different than that?

> - it would be really nice to not have to deal with the complexity of
accounts versus users within the auth system. Like if we could just have
the notion of accounts and provide good client-side CLI tooling to manage
multiple accounts that seems like it might be simpler on our end. Just a
thought.

I agree it would be nice but I do not see how to do that. Suggestions welcome. Right now, github auth for our own customer authenticating to the diff server seems like the best/easiest/most-common plan. But that just authenticates the user. The real primary entity in our system is a group of users acting on behalf of some org. So we need some way to map between those two :-/.

> - is it a requirement that auth specific errors of each kind are returned
with fine grain fidelity to the binding or user code?

Yes. The current thing does this, but any new thing would as well.

> - is it a requirement that eventually there's a mechanism for replicache the company to help developers recover replicache account credentials or information if they are lost?

I would say there has to be some mechanism to get back into your account if locked out. It doesn't need to be us that does it (in the case of delegated auth like github).

**Comment by phritz** [comment]
re more sophisticated customers - yes i am saying something different but now that we are talking about it i do not think we should worry about it. was thinking eg a customer wanting to auth our diff servers to ensure that the client view is only served to our diff server and not eg to someone who stole the users credentials. forget this concern.

re users and groups i'm saying would love to talk about how to enable groups of people to collaborate on r accounts *without having to introduce a notion other than account to the r system*. like replicache only knows about accounts but we have a separate account system that replicache knows nothing about that enables users to collaborate on accounts, but without the notion of groups or customer users being represented in the auth code replicache itself uses. so yes we need a mapping, i'm hoping we can keep it out of the r implementation itself, which is maybe obivous. sorry if that is not clear, can splain voice if still not.

**Comment by phritz** [comment]
to be clear about authing our diffservers: a company like google would want to do that for DOS protection and as a good defense in depth. small companies might want something like to know the ips that we are requesting from, but only maybe :)

**Comment by aboodman** [comment]
I'm going to use this bug to represent whatever we do for both diff-server auth and data-layer auth, and the relevant client changes.

**Comment by phritz** [comment]
following up on this so we are all on the same page. from another source here are aaron's restated requirements:
- Clients make requests on behalf of Replicache accounts. Diff-server must be able to authenticate which account a client is communicating on behalf of (e.g., for billing).
- Diff-server proxies requests to data-layer. Client requests to data-layer on behalf of a user. Data layer must be able to authenticate which user client is requesting on behalf-of (e.g., for security/privacy).
- Diff-server should be able to respond to replicache-client even if data-layer is unavailable.
Work to support authentication specific to Replicache (above what would be needed in absensce of Replicache) by customer should be minimized.
- if the customer data layer is compromised we would not like that to mean that all users data are compromised forever

Non-requirements

- Data layer does not need to authenticate which client is requesting (all clients for a user have identical privileges).

and here are my notes about requirements:

- Minimize effort on the customer’s part, ideally to zero.
- Clients must be associated with an account. Said another way, a client that is not associated (somehow) with an account cannot pull.
    - Of course, nothing stops us from turning protection off on an account basis, but in general it seems like this should be true.
    - We want this association for potentially many reasons: eg billing, debugging, etc. as well as to just not have anyone on the internet be able to invoke our endpoints.
- When a client calls pull it can receive only data fetched from the clientview as part of this or a previous pull by this client. Ie not from another client’s clientview.
- When a client calls pull it can only receive data from the data layer of the account it is associated with (and not some other account’s data layer or a random url on the internet).
- Client should be able to pull whether or not datalayer is responsive
- Client must be able to auth to the clientview in a way that indicates the data layer the data layer user the clientview request is for.
    - Currently this is by client passing an opaque string to DS which is passed to data layer in Authorization. Client view auth token distribution, update, etc is outside of replicache.
- Diffserver needs to know the data layer url to fetch from during a pull request
    - Currently this url is part of the account. It could be passed in by the client, i’m not clear on the tradeoffs.

Non-requirements

- We do not need a way to invalidate any replicache credentials or secrets that might be stolen from the client.
- We do not need a way to replace or update replicache credentials or secrets that might exist in the client.
- We do not need a way to restart a busted client. The solution is to abandon the old client info and start fresh.
- dont require the customer to distribute secrets with the app that grant access to user data

Proposal

Here's what aaron and i talked about, i think:
- at init time the client generates a unique unguessable identifier, the clientid. this clientid is a secret, anyone who has it can fetch the corresponding user's data in perpetuity. the clientid is passed along in the pull request and identifies that client's cache. (this is already how it works, so yay)
- we avoid having the customer store (or maybe leak) a secret, the clientid, by sending a secret function of the clientid to the data layer when sending mutations. the data layer doesnt care that it has the actual clientid when tracking lastmutationid, just that each client sends it a unique string.
- at account creation time an unguessable accountid is generated. the diffserver needs the accountid to know which url to fetch the client view from and for future things like billing. the accountid should be unguessable to prevent one customer from being able to cause fetches to another customer's data layer, make charges to it, etc. the accountid is easy to discover once distributed of course, but raises the bar to spamming etc, and seems prudent. the accountid is currently passed in the authorization header from client to diffserver and checked there.
- the user authenticates to the data layer by passing an opaque token in the pull request (datalayerauth) which is place in the authorization header of diffserver's clientviewrequest to the data layer.

thiis pretty much how it works already, except for:
- accountids should be unguessable
- send f(clientid) to data layer in mutations
- be able to signal to customer app that auth to data layer was no good

yes?

**Comment by aboodman** [comment]
I think this is done right?

**Comment by phritz** [comment]
Not really done. The "this is done except for" list has two things we dont do yet:

- accountids should be unguessable
- send f(clientid) to data layer in mutations

**Comment by phritz** [comment]
For the 'send f(clientid) to data layer' part of this, background:
- currently client db has a clientid that it sends to both the batch endpoint during push and the diffserver during pull. the batch endpoint uses clientid as a key to track last mutation id received. the client view accepts client id so it can look up the last mutation id to return with its client view response (so that the client knows which mutations have been included).
- this is a problem because the clientid is used by the diff server to key the user's data; if you have the same app and you know it you can fetch that client's data from the diff server. 
- it is not the case that the diff server and data layer must use the same client id; the data layer just needs something that is consistent and the diff server uses it as a key (the dataset name)

Proposal:
- the threat model we consider is the client id leaking from the data layer, NOT the client id being stolen from a specific device
- split the two roles the clientid currently serves. have:
   - `deviceID` -- a secure guid that the data layer sees via batch pushes and client view pulls. This is not private information (data layer is protected by user auth token), it is just a cookie.
   - `cacheID` -- a secure guid that is sent to the diff server during pull and the diff server uses as the dataset name. This is private information. If stolen, other users of the app can download the user's data from the diffserver.

(btw we moving from client* to device* yes?)

**Comment by aboodman** [comment]
The idea of splitting the roles makes sense to me, but there's another wrinkle in the naming issues here:

* We call the code that you link into your app _the client_, or _replicache client_.
* You can actually create multiple physical separate caches on the same app. We do this in the TODO sample app for each user. Each has a unique ID. We currently call this ID _client ID_.
* Each unique physical cache on a device must track its mutations separately, so "device ID" isn't technically accurate (it doesn't identify a device, it identifies a cache).

So to me the best naming may actually be to adopt your "cache" nomenclature, but to distinguish the two cases:

* `cacheID` -- guid that identifies the cache to the datalayer so that `lastMutationID` can be tracked.
* `branchID` -- guid that identifies the branch to read and write from on diffs. Could also use something like `storeID` but we previously decided to just adopt git terminology. In this context it's a bit odd, but this name is only used by us internally.

**Comment by phritz** [comment]
No longer relevant w/o the diffserver.
