### ISSUE TITLE
20MB client view max: what if it's a feature? (not a bug)

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#82]
This is a bit of an ill-formed idea, but it's been bouncing around in my head for awhile and I want to get it out.

Right now our client view max size is 4-5MB compressed. This is determined by, ultimately, aws lambda. We generously call this 20MB uncompressed :).

Even with the generous estimate, there are a number of problems with this, all kind of inter-related:

- 20MB is not enough for many applications
- Many applications also want blobs, but our client view is JSON. JSON is great for many reasons, but this blob thing is a big issue. Also if we supported blobs they'd immediately blow this 20MB limit up.
- Even if we upped the 20MB limit by moving off lambda for the diff server, hundreds of MB is a lot to serve with the current monolithic client view approach on a number of levels, leading to ideas like differential sync

So here's a thought. What if the model for a Replicache instance is not a single monolithic Replicache instance but dozens (hundreds?) of little ones.

What if a Replicache client view isn't analogous to e.g., a SQLite database, but instead analogous to a mongo db Document. And a Replicache database would host *lots* of these documents.

This is kind of a big idea, so I'll stop there. But I think there are lots of interesting side-effects of this change, many good, some not as good.

**Comment by phritz** [comment]
Thinking about this. But real quick: 

>  but this blob thing is a big issue

In my view it's the kind of thing that a certain kind of engineer thinks is a big deal (what? you want me to base64-encode my blobs? but that's so inefficient!) but for many engineers in many projects is not a real issue in practice. At millions of users or with hundreds of megs of data or with really tight performance goals it probably is but think it's common to overvalue the efficiency and undervalue the simplicity of having everything fit the same data model.

But I also recognize that it IS "a big issue" in the sense that those engineers THINK it is a big issue, even if in practice an objective viewpoint would be that it is not.

**Comment by aboodman** [comment]
I only mean it's an issue in the sense that dozens of blobs is going to blow your client view limit. So in practice you can't really use blobs.
